spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BookStore
    username: postgres
    password: 5597
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  security:
    admin:
      username: Admin@Outlook.com
      password: Admin123
    jwt:
      secret-key: 684C2F5961577166467076783637326D4E385A754E454A2B4D6F6E772F52376E6931587A3355612B306A55595341504D7774484F6B76782F56615164363047320A
      expiration: 60000000 # a day
      refresh-token:
        expiration: 604800000 # a week